# Generated by Django 5.0 on 2023-12-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_chat_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
